#!/bin/bash

set -e

if [ -x node_modules/roots/bin/roots ] ; then
    roots=./node_modules/roots/bin/roots
elif [ "$(which roots)" != "" ] ; then
    roots=`which roots`
else
    echo "Grow some roots, man!"
    exit -2
fi

echo "roots found in ${roots}"

$roots compile --no-compress

rm -rf tmp
cp -R public tmp
git checkout gh-pages
cp -R tmp/* .
git add .
git commit -a -m "Update release - `date -u`"
# Need to add the 5apps remote:
#   git remote add 5apps git@5apps.com:remotestorage_remotestorageio.git
git push 5apps gh-pages:master
git push origin gh-pages
git checkout master
rm -rf tmp
