#!/bin/bash

set -e

if [ "$(which roots)" != "" ] ; then
    roots=`which roots`
elif [ -x node_modules/.bin/roots ] ; then
    roots=node_modules/.bin/roots
else
    echo "Grow some roots, man!"
    exit -2
fi

echo "roots found in ${roots}"

$roots compile

rm -rf tmp
cp -R public tmp
git checkout gh-pages
cp -R tmp/* .
git add .
git commit -a -m "Update release - `date -u`"
git push origin gh-pages
git checkout master
rm -rf tmp
